config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("movies/", include("movies.urls", namespace="movies")),
    path("books/", include("books.urls", namespace="books")),
    path("categories/", include("categories.urls", namespace="genres")),
    path("people/", include("people.urls", namespace="people")),
    path("users/", include("users.urls", namespace="users")),
    path("favs/", include("favs.urls", namespace="favs")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core.views import resolve_home, resolve_search

app_name="core"

urlpatterns = [
  path("", resolve_home, name="home"),
  path("search", resolve_search, name="search")
]

reviews/urls.py
from django.urls import path
from . import views


app_name = "reviews"

urlpatterns = [
  path("create/<int:pk>", views.CreateReviewView.as_view(), name="create"),
  path("delete/<int:pk>", views.delete_review, name="delete"),
  path("<int:pk>/", views.my_review, name="review"),

]

reviews/models.py
from django.db import models
from core.models import CoreModel

class Review(CoreModel):

  """ Review Model """ 

  created_by = models.ForeignKey("users.User", on_delete=models.CASCADE, related_name="reviews")
  
  text = models.TextField()
  
  movie = models.ForeignKey("movies.Movie", on_delete=models.CASCADE, related_name="reviews", null=True, blank=True)
  
  book = models.ForeignKey("books.Book", on_delete=models.CASCADE, related_name="reviews", null=True, blank=True)
  
  rating = models.IntegerField()

  def __str__(self):
    return self.text

reviews/forms.py
from django import forms
from . import models


class CreateReviewForm(forms.ModelForm):

    rating = forms.IntegerField(max_value=5, min_value=1)

    class Meta:
        model = models.Review
        fields = (
            "text",
            "movie",
            "book",
            "rating",
        )

    def save(self, *args, **kwargs):
        review = super().save(commit=False)
        return review

reviews/views.py
from django.shortcuts import redirect, reverse, render
from . import forms, models
from django.views.generic import FormView


class CreateReviewView(FormView):

    form_class = forms.CreateReviewForm
    template_name = "reviews/detail.html"

    def form_valid(self, form):
      review = form.save()
      review.created_by = self.request.user
      review.save()
      return redirect(reverse("core:home"))

def my_review(request, pk):
  reviews = request.user.reviews.all()
  return render(request, "reviews/my_review.html",{"reviews":reviews})

def delete_review(request, pk):
  review = models.Review.objects.filter(pk=pk).delete()
  return redirect(reverse("core:home"))

templates/reviews/detail.html
{% extends "base.html" %}

{% block page_title %}
  Review
{% endblock page_title %}


{% block content %}
  <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

    <form method="POST" class="w-full">
        {% csrf_token %}

        {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
                <span class="text-red-700 font-medium text-sm">{{error}}</span> 
            {% endfor %}
        {% endif %}

        {% for field in form %}
            <div class="rounded-sm py-2 font-light text-lg w-full text-left border border-gray-600 px-3 w-full mb-2{% if field.errors %}has_error{% endif %} focus:outline-none">
                {{field.label}}
                {{field}}
                {% if field.errors %}
                    {% for error in field.errors %}
                        <span class="text-red-700 font-medium text-sm">{{error}}</span> 
                    {% endfor %}
                {% endif %}
            </div> 
        {% endfor %}

        <button class="text-center rounded-sm py-5 font-light text-lg w-full bg-blue-400 text-white">Create</button>
    </form> 
  </div>
{% endblock content %}

templates/reviews/my_review.html
{% extends "base.html" %}

{% block page_title %}
  Review
{% endblock page_title %}


{% block content %}

  <div class="p-4 py-8">
    <h1 class="font-bold text-2xl">Review</h1>
    <div class="my-8">
      {% for review in reviews %}
        <div class="mb-4">
          {% if review.book %}
            <span class="font-medium text-lg">{{review.book}} :</span>
          {% else %}
            <span class="font-medium text-lg">{{review.movie}} :</span>
          {% endif %}
          {{review}}
          <a class="text-blue-400 hover:text-blue-600 text-sm text-white mt-4 py-1 px-2 rounded" href="{% url 'reviews:delete' review.pk %}">delete</a> 
        </div>
      {% endfor %}
    </div>
    <a class="bg-blue-400 hover:bg-blue-600 text-white font-bold mt-4 py-2 px-4 rounded" href="{% url 'reviews:create' user.pk %}">Create Review</a>

  </div>


  


{% endblock content %}